steps:
  - name: Check out repository
    uses: actions/checkout@v4

  - name: Install required packages
    run: |
      sudo apt update
      sudo apt install git wget lz4 tar openssl python3 -y

  - name: Download recovery image
    run: |
      wget https://we.tl/t-MKbgvT5uQT -O recovery.img

  - name: Make scripts executable
    run: |
      chmod +x magiskboot
      chmod +x patcher-minimal

  - name: Patch the recovery image
    run: ./patcher-minimal

  - name: Upload patched image
    uses: actions/upload-artifact@v4
    with:
      path: ./patched-recovery.img
      name: Patched Recovery Image
      retention-days: 15
        compression-level: 0
        overwrite: true
        
    - name: Upload keys for patched image
      uses: actions/upload-artifact@v4
      with:
        path: /home/runner/work/fastboot-patcher/fastboot-patcher/keys/*.*
        name: Patched Image Key Bundle
        if-no-files-found: error
        retention-days: 15
        compression-level: 0
        overwrite: true
